2024-02-15 23:11:24,499: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-02-15 23:11:25,609: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-02-15 23:11:25,610: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-15 23:11:25,611: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-02-15 23:11:25,611: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-15 23:11:25,612: root: INFO: [34mExecuting the on_trading_iteration lifecycle method at 2024-02-15 23:11:25[0m
2024-02-15 23:11:25,612: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-15 23:11:25,623: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-15 23:11:26,069: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'order_type'
2024-02-15 23:11:26,073: root: ERROR: Traceback (most recent call last):
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 859, in run
    self._run_trading_session()
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 810, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 279, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 303, in func_output
    result = func_input(self, *args, **kwargs)
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 87, in func_output
    return func_input(self, *args, **kwargs)
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\strategies\strategy_executor.py", line 381, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\KG\anaconda3\envs\quant\lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\KG\Documents\GithubFiles\MyQuantsFinance\2_strategies\strat_sentiment_lumibot.py", line 67, in on_trading_iteration
    order = self.create_order(
TypeError: Strategy.create_order() got an unexpected keyword argument 'order_type'

2024-02-15 23:11:26,076: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-15 23:11:26,090: root: INFO: Backtesting finished
2024-02-15 23:11:26,093: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-02-15 23:11:26,292: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
2024-02-15 23:11:26,292: backtest_stats: INFO: Backtest took 0:00:01.795148 for a speed of 0.000
